data_ingestion:
  bucket_name : "ml_project_02"
  bucket_file_names :
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 128
  loss: binary_crossentropy
  optimizer: adam  
  metrics:
    - mae
    - mse
